enableGlobalCache: true

nmHoistingLimits: workspaces

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: .yarn/plugins/@yarnpkg/plugin-compat.cjs

npmScopes:
  candlefinance:
    npmAuthToken: '${GITHUB_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
